sudo: required
services:
- docker
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
install:
- yarn
script:
- export ENV_FILE=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "prod"; else echo
  "stage" ; fi`
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif [
  "$TRAVIS_BRANCH" == "develop" ]; then echo "stage"; else echo "dev-$(git rev-parse
  --short HEAD)" ; fi`
- docker build --no-cache -t jincort/frontend-wallets-develop:${TAG} .
- docker run --rm -v $(pwd):/usr/src/app jincort/frontend-wallets-develop:${TAG} yarn
- docker run --rm -v $(pwd):/usr/src/app jincort/frontend-wallets-develop:${TAG} cp
  -r .env.${ENV_FILE} .env
- docker run --rm -v $(pwd):/usr/src/app jincort/frontend-wallets-develop:${TAG} yarn
  build
- docker run --rm -v $(pwd):/usr/src/app jincort/frontend-wallets-develop:${TAG} yarn
  run lint
- docker run --rm -v $(pwd):/usr/src/app jincort/frontend-wallets-develop:${TAG} yarn
  run test:CI
after_success:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif  "$TRAVIS_BRANCH"
  == "develop" ]; then echo "stage"; else echo "dev-$(git rev-parse --short HEAD)"
  ; fi`
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile.prod --no-cache -t jincort/frontend-wallets:${TAG} .
- docker push jincort/frontend-wallets-develop:${TAG}
- docker push jincort/frontend-wallets:${TAG}
notifications:
  slack:
    secure: mpvcu6u1+cstyt0yPqyDqMRePWJjCEbHsBfe86e/Qv4LUAmOAavXG83LDyL7+SA331Qb4H1GdIwyBMsfG02hqmWarOk/EKTYnoTzzipiO+RS6M+y2kc1cRVq8l3f5l4WiaPVH7uSR4Nu74YPIZaIqFdfmSSu2iYl0Hq6hUumfg9bMmany9qSiTqATGksUFp5b2vGU5GI474QYBckGinuJ3uBiWUR16sPfhHQ7Ge80HYXIneQeYoybINKOzY8EnNL3qZ9zvWc8qtk2OIpGSqitz+1lBiloWFB58sm7S1Uf/z4B5DJHl5ws/zWSNBTyvGkXJbq0mORzgMtR4QUxXu9DIveyRJBfrS7beWV9Z6bYJ76z0s53O/kj425JQxjkQmxw7oGocNKKeS6060t+b4n501DZbh7MWxBEQKuq20spGfchRsKdJqBEEAKHw967PhFTTJNpbOzUIiMkYOofMoef55VNnCxHZ683BE8i4TnfEKgeKsMQQ95DtxxdbR6qXwOtUsba7zycxN2WrEKZOi/nrebJeHUwQBEGuIDenNup4PQnwHDmWok8Uq8nKMY37UceRUxbNiW86DyYUWoHI6yHSEQRrq9O1JV5+rMCoxfV6cwoiWGZLokD2LPNyT0/q1bk3hFImr99a+rpMmTn2NDARSP8oSRn46dskc8mGUm8lc=
env:
  global:
  - secure: Da038nwGxpo2ojvOIwh+uJMLfJTZEnauOvDNcaCWryztgAbBD8f1F7wRb5qZGLmmGkFTbvhmBmjJ22vbyPtp9JSZsE0RIoTILBwwZ7Nswb69MkyIacClih+Ancr1qd0VsuXmYKVtdUCb0putWIJdp0f4ZJqXF0B2WUNKBV4tF78zdCoKHrg036h8m7hPtxoW9ZMO2GH7GLYN47ucP6LC54zywvlLYP9r4pHu0AeyAS0FAfsTnEbtKdMie1yqzMmu+faXzhQSL/UVievLEsDLYoMaz+E+oxx9c9rNbDgywTEZ3zl2Y8wuGrWcTY2i4vhLyhkrySJ9DeoKum+/G3NcGusqAHggJqO7YFU7uKbvrXrd9oUQj5M0b0Wnk6FY9D4+fRcDuZIcr5pKdHUhR4MFZST3dzI5bsSpCjBvrrzoqmN6irOV4a6o+yNGPyf0OshXFCHLJM6G3EQK6ZTxJWLq3nDz/YDFspx77cyeR4jnpwITE6teT0j1mpNQVS5Kjhdz9EzOHh3itJSbiyCZ54WpDZAjipPQFXhoS+EJWZqWdKfzfaNgRSW2eQYnq35gk5RDZUM4R9goafHV+PEmju7CR111ExSbLAVUMMQQIK2Ko34mD3boU6bx/fRLcB+lpTghtxk5GwYPLnKJK6bFs3IzZnoTJUQvjOOOjpduXc6o73M=
  - secure: V+0VZPaFWBRnI/5uvecJnBOQjtaJmG3ZrZbf3jrAUNL2EnOR34GDPmRLuVMpdKlDMB6b5BvidXuE0IdbcEafnVTw9cfql9wyidnt88OEIg/euI0L8PQwUp/cHDZIT63BOPnC1HUtfYX+zI3OPazcylG9LM7G4PW0+ileyaE6PTIirHAT9klH1hq4mw5iprU4MIVHdPAVQygydTKxqKVcbAzElHFCR2QG00WCiApq0koRnazbwsaK7XpjQEiQqhGFOL/g3OW+euwJ3rwRc/I9sVUUOIR0ZrPozfdiYtl/qcxuREL7J81SLCNTZqDfz/hO0rLz3ZdNiZp51c7ihe/6JOKXgkhhovoCsLc0jLqSz2JQFLPZmWFXFPQruAeuhALZrWMTGjEa/Oi7oalSoAsjyaX6jd013RyVDinvuVn/teWIP88kDXCMtMyPe7OERa51z3/5SO1XnFnJ8NeUiHqpvqOM6RdUL5so+zkQ2wxYPCdZrdF+pS6QU90USRo+0jYZ/7ok0AMWVJYgWUxPn+GjinduXWYGx7j/KTm842UGFtfiSPfH8CdevaoDWbXsSv+V7m2hxqfh8YJ11lTGpCPrR+c82Jlx9x3+4pJmh24bb1u9gB0MKYMar9QRBOrAwbeJzbd3WpQdRK8cxPN9ny+iLSjLegYd7MFj6aE8NgSa0eY=
